In [1]:
#importing libraries that might come in handy during the quiz
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
#testing to see which option is likely to be correct for question 1
a = [1, 2, 3]
b = [2, 3]
a.extend(b)
#a.append(b)
print(a)

[1, 2, 3, 2, 3]


In [3]:
print(np.identity(3)) #testing to see if this truly creates an identity matrix; it does

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#np.array[(1, 2, 3)] #testing to see if python would accept this; it doesn't

In [5]:
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv" #link to the dataset

In [6]:
read_file = pd.read_csv(url)

In [7]:
df = pd.DataFrame(read_file)

In [8]:
df.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [9]:
df.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean() #to find out fuel type code with the lowest average fuel cost per unit burned

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [10]:
df.describe() #to obtain standard deviation and 75th percentile of the measure of energy per unit

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [11]:
df["fuel_qty_burned"].skew(axis = 0, skipna = True ) #to obtain skewness for  fuel quantity burned

15.851495469109503

In [12]:
df["fuel_qty_burned"].kurt(axis = 0, skipna = True) #to obtain kurtosis for fuel quantity burned

651.3694501337732

In [13]:
df.isnull().any() #to obtain the feature with missing values; it is fuel_unit

record_id                       False
utility_id_ferc1                False
report_year                     False
plant_name_ferc1                False
fuel_type_code_pudl             False
fuel_unit                        True
fuel_qty_burned                 False
fuel_mmbtu_per_unit             False
fuel_cost_per_unit_burned       False
fuel_cost_per_unit_delivered    False
fuel_cost_per_mmbtu             False
dtype: bool

In [14]:
df["fuel_unit"].isnull().sum() #in order to obtain total number of missing values

180

In [15]:
df.shape #in order to obtain total rows in the dataframe

(29523, 11)

In [16]:
print((180/29523) * 100)

0.609694136774718


In [17]:
print(29523-180)

29343


In [18]:
df.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [19]:
df.groupby("report_year")["fuel_cost_per_unit_delivered"].mean() #in order to obtain highest average fuel cost per unit delivered

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64

In [20]:
new_f = df.dropna() #new dataframe without missing values

In [21]:
new_f.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29343.000000  29343.000000     2.934300e+04         29343.000000   
mean         118.507037   2005.819105     2.609171e+06             8.477481   
std           74.241226      7.019855     8.798699e+06            10.537478   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.375050e+04             1.024000   
50%          122.000000   2006.000000     2.524640e+05             5.763072   
75%          176.000000   2012.000000     1.424218e+06            17.000000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29343.000000                  2.934300e+04   
mean                  209.756592                  9.230343e+02   
std                  2863.194789                  6.898652e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.230000                  3.793000e+00   
50%                    26.039000                  1.749000e+01   
75%                    47.172000                  4.220850e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29343.000000  
mean             18.543975  
std            2097.367750  
min             -41.501000  
25%               1.950000  
50%               4.140000  
75%               7.752000  
max          359278.000000

In [22]:
coal_df1 = df.loc[(df.fuel_type_code_pudl == "coal") & (df.report_year == 1998)] #using loc to select particular rows 

In [23]:
coal_df2 = df.loc[(df.fuel_type_code_pudl == "coal") & (df.report_year == 1994)] #using loc to select particular rows

In [24]:
coal_df1.head()

record_id  utility_id_ferc1  report_year  \
4618   f1_fuel_1998_12_1_0_7                 1         1998   
4619  f1_fuel_1998_12_1_0_10                 1         1998   
4620   f1_fuel_1998_12_4_0_1                 4         1998   
4622   f1_fuel_1998_12_4_0_4                 4         1998   
4624   f1_fuel_1998_12_6_0_1                 6         1998   

          plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
4618    rockport total aeg                coal       ton        4965881.0   
4619  rockport total plant                coal       ton       10000938.0   
4620           units 1 - 3                coal       ton        1974682.0   
4622                unit 4                coal       ton         385512.0   
4624          clinch river                coal       ton        1834553.0   

      fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
4618               17.198                     19.282   
4619               17.196                     19.280   
4620               22.266                     26.550   
4622               22.330                     26.550   
4624               24.534                     30.936   

      fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
4618                        19.338                1.126  
4619                        19.340                1.122  
4620                        26.540                1.190  
4622                        26.540                1.190  
4624                        30.013                1.261

In [25]:
coal_df2.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
5  f1_fuel_1994_12_2_0_13                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
5   e. c. gaston-unit 5                coal       ton        2124933.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
5               23.922                      44.24   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
5                         43.25                1.850

In [26]:
coal_df1.groupby("report_year")["fuel_cost_per_unit_burned"].sum() #sum fuel cost per unit burned of coal in 1998

report_year
1998    11902.597
Name: fuel_cost_per_unit_burned, dtype: float64

In [27]:
coal_df2.groupby("report_year")["fuel_cost_per_unit_burned"].sum() #sum fuel cost per unit burned of coal in 1994

report_year
1994    14984.572
Name: fuel_cost_per_unit_burned, dtype: float64

In [28]:
print(((11902.597-14984.572)/14984.572)*100) #calculation of percent change in fuel cost per unit burned in 1998 compared to 1994

-20.567654518260518
